### ISSUE TITLE
URLEncode hook doesn't work

### ISSUE THREAD

**Issue by anjeylink** [t3kit/t3kit_extension_tools#10]
URLEncode hook doesn't work with new realurl

**Comment by jozefspisiak** [comment]
Was it removed completely or only changed name? I can investigate tomorrow. Also @bobriusNT is looking into this for a different project.

**Comment by anjeylink** [comment]
i think it was just changed. hooks are registers now here:  
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['encodeSpURL_postProc']

also hook in "t3kit_extension_tools" is checking if class name is "tx_realurl_advanced" or "tx_realurl", but these classes doesn't exist anymore, so condition never works.

**Comment by bobriusNT** [comment]
actually, encodeSpURL_postProc is not good for us, because it calls after url is generated and there's no access to segments of path and no such things as title and processed title. I tried different workarounds there but nothing helped.

also, in method where string converting is happens (convertToSafeString()) there is a line:
// TODO Post-processing hook here
so maybe we will have something there in future :)

the only way that worked for me was extending the realurl utility class and adding character replace there - something like this:
class Utility extends \DmitryDulepov\Realurl\Utility {
  public function convertToSafeString($processedTitle, $spaceCharacter = '-', $strToLower = true) {
    $processedTitle = str_replace(array('ä','å','ö','Å','Ä','Ö'), array('a','a','o','a','a','o'),$processedTitle);
    ......
  }
}

p.s. for some reason this was not working over typoscript class mapping, so I used $GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'] for this

**Comment by jozefspisiak** [comment]
That is fine, just don't forget to call parent there and create a pull request :)

**Comment by dmh** [comment]
Hi guys,
Do you have any updates according this issue?

**Comment by anjeylink** [comment]
Hi, i did it as Andriy suggested.
https://github.com/t3kit/t3kit_extension_tools/commit/c657d54f3f248fba611b6e08bccc6efdd16331c7

with only difference - you can add more characters in extension manager
